out/production/fatcatty/config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: { registrations: "registrations"}
  mount Ckeditor::Engine => '/ckeditor'
  get 'posts/index'
  get 'posts/new'
  get 'posts/create'
  get 'posts/showrandom'
  get 'posts/delete'
  get 'works/delete'
  get 'works/new'

  root 'posts#index'
  resources :works, only: [:index, :show, :create, :destroy]
  resources :archives, only: [:show, :index]
  resources :posts, only: [:create, :show, :destroy, :index, :feed]
  get 'tags/:tag', to: 'posts#index', as: "tag"
  resources :feeds, only: [:index]

end

out/production/fatcatty/app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

out/production/fatcatty/app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

out/production/fatcatty/app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

out/production/fatcatty/app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

out/production/fatcatty/app/models/post.rb
class Post < ActiveRecord::Base
 has_many :taggings
 has_many :tags, through: :taggings, dependent: :destroy
 validates :title, presence: true


  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    self.tags.map(&:name).join(", ")
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).posts
  end

  def self.tag_counts
    Tag.select("tags.id, tags.name, count(taggings.tag_id) as count").
      joins(:taggings).select("taggings.tag_id, tags.id, tags.name")
  end

  def to_param
    "#{id} #{title}".parameterize
  end


end

out/production/fatcatty/app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :posts, through: :taggings

  def self.counts
    self.select("name, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id, name")
  end
end

out/production/fatcatty/app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

out/production/fatcatty/app/models/work.rb
class Work < ActiveRecord::Base
  validates :title, presence: true
  has_attached_file :image,
  source_file_options: { all: '-auto-orient' },
  styles: { original: "", thumb: "200x200#" }
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

out/production/fatcatty/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token
end

out/production/fatcatty/app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
def index
    @posts = Post.all
    @post_months = @posts.group_by { |t| t.created_at.beginning_of_month }
end
end

out/production/fatcatty/app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  layout false

  def index
    @posts = Post.order('created_at DESC')
    @title = "(๑ↀᆺↀ๑) (๑ↀᆺↀ๑) (๑ↀᆺↀ๑)"
    @updated = @posts.first.created_at unless @posts.empty?
  end
end

out/production/fatcatty/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show
    @post = Post.find(params[:id])
  end

  def showrandom
    @post = Post.offset(rand(Post.count)).first
    redirect_to @post
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag])
      @postspag = Post.paginate(page: params[:page], per_page: 12).order('created_at DESC')
    else
      @posts = Post.paginate(page: params[:page], per_page: 12).order('created_at DESC')
      @postspag = Post.paginate(page: params[:page], per_page: 12).order('created_at DESC')
    end
  end

    def destroy
      Post.find(params[:id]).destroy
      redirect_to root_path
    end

    def create
     @post = Post.new(post_params)
       if @post.save
         redirect_to root_path
       else
         format.html { render root_path }
       end
     end
   end

  private
   def post_params
     params.require(:post).permit(:title, :body, :score, :all_tags)
   end

out/production/fatcatty/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  before_action :one_user_registered?, only: [:new, :create]

  protected

  def one_user_registered?
    if ((Admin.count == 1) & (admin_signed_in?))
      redirect_to root_path
    elsif Admin.count == 1
      redirect_to new_admin_session_path
    end
  end

end

out/production/fatcatty/app/controllers/works_controller.rb
class WorksController < ApplicationController
  helper_method :sort_column, :sort_direction

  def new
    @work = Work.new
  end

  def index
#   @works = Work.all
  @works = Work.paginate(page: params[:page], per_page: 12).order('created_at DESC')
  end

  def show
    @work = Work.find(params[:id])
  end

  def destroy
     Work.find(params[:id]).destroy
     flash[:success] = "work deleted"
     redirect_to works_path
  end

  def create
     @work = Work.new(work_params)
      if @work.save
          redirect_to works_path
      else
    end
  end

private

# Use strong_parameters for attribute whitelisting
# Be sure to update your create() and update() controller methods.

def work_params
  params.require(:work).permit(:image, :title)
end

end

out/production/fatcatty/app/helpers/application_helper.rb
module ApplicationHelper
  def tag_cloud(tags, classes)
  max = tags.sort_by(&:count).last
  tags.each do |tag|
    index = tag.count.to_f / Integer(max.count) * (classes.size - 1)
    yield(tag, classes[index.round])
    end
  end

def sortable(column, title = nil)
  title ||= column.titleize
  css_class = column == sort_column ? "current #{sort_direction}" : nil
  direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
  link_to title, {:sort => column, :direction => direction}, {:class => css_class}
end

end

out/production/fatcatty/app/helpers/archives_helper.rb
module ArchivesHelper
end

out/production/fatcatty/app/helpers/art_helper.rb
module ArtHelper
end

out/production/fatcatty/app/helpers/pictures_helper.rb
module PicturesHelper
end

out/production/fatcatty/app/helpers/posts_helper.rb
module PostsHelper
  def tag_links(tags)
    tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(", ") 
  end
  
  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size-1)
       yield(tag, classes[index.round])
     end
  end

end

out/production/fatcatty/app/views/archives/index.html.erb
<div class="archiveList">
	<h2>archive</h2>
	<% @post_months.sort.reverse.each do |month, posts| %>
	<h5><%=h month.strftime("%B %Y") %></h5>
	<ul>
		<% for post in posts %>
		<li><%=h link_to post.title, post_path(post) %></li>
		<% end %>
	</ul>
	<% end %>
</div>

out/production/fatcatty/app/views/layouts/_nav.html.erb
<div class="navvy">
  <div class=fatcattyLogo>
  <%= link_to image_tag("logonav.png"), root_path %>
  </div>
<div class="navItems">
  <ul>
    <li class="dropdown"><a href="../" class="dropbtn"><%= image_tag("archive.png") %> blog</a>
      <div class="dropdown-content">
        <a href="../archives"><%= image_tag("archive.png") %> archives </a>
        <a href="../posts/showrandom"><%= image_tag("archive.png") %> random </a>
      </div>
    </li>
    <li><a href="../works" class="dropbtn"><%= image_tag("gallery.png") %> works</a></li>
    <li class="dropdown"><a href="javascript:void(0)" class="dropbtn"><%= image_tag("about.png") %> more</a>
      <div class="dropdown-content">
        <a href="../golf"><%= image_tag("golf.png") %> golf </a>
        <a href="../ssc"><%= image_tag("sscico.png") %> smileysuncoin </a>
        <a href="../carfool"><%= image_tag("bullet.png") %>carfool </a>
      </div>
    </li>
    <li><a href="../shop"><%= image_tag("sscico.png") %> shop </a></li>
    <li><a href="../tunes"><%= image_tag("music.png") %> tunes </a></li>
    <li><a href="https://sideyeti.com"><%= image_tag("bullet.png") %> sideyeti </a></li>
    <li><a href="../abt" class="dropbtn"><%= image_tag("random.png") %> about</a></li>
    <% if admin_signed_in? %>
      <li><a href="../admins/sign_out" class="dropbtn"><%= image_tag("bullet.png") %>logout</a></li>
    <% else %>
      <li><a href="../admins/sign_in" class="dropbtn"><%= image_tag("bullet.png") %>login</a></li>
    <% end %>
  </ul>
</div>
</div>

out/production/fatcatty/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-80744770-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-80744770-1');
    </script>
    <title><%= content_for?(:title) ? yield(:title) : "(๑ↀᆺↀ๑) fatcatty" %></title>
    <script src="https://cdn.ckeditor.com/4.14.0/standard/ckeditor.js"></script>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <%= favicon_link_tag 'favicon.ico' %>
    <%= auto_discovery_link_tag :atom, "/feeds.atom" %>
    <%= auto_discovery_link_tag :rss, "/feed.rss" %>

    <script type="text/javascript">
      for(var instanceName in CKEDITOR.instances)
          CKEDITOR.instances[instanceName].updateElement();
    </script>

  </head>
  <body>
    <div>
      <%= render "layouts/nav" %>
      <div class="bContainer">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

out/production/fatcatty/app/views/pages/abt.html.erb
<div class= "large-9 columns" id="aboutcontainer" style="float:left;">
  <p>part of the b@b family</p>
  <p>email me @ <%= mail_to "anything@wmmcorp.com" %> to talk</p>
  <p><%= link_to 'play me', 'https://www.chess.com/member/denago' %> on chess.com, 48 or 72 hours please</p>
  <p>send bitcoins: 16pd6vALjaDnnN8eA1orVSi9s1SfyDteEz</p>
  <p>tip me <span style="color:orange;">BAT</span> using your BRAVE browser</p>
  <p><%= link_to image_tag("rss.png"), feeds_path %><%= link_to(' subscribe to the rss feed so that you never miss a post', feeds_path) %></p>
  <p>please create dont be gutta mane</p>
  <p><%= link_to 'check out transplant vintage', 'https://www.transplantvintage.com' %></p>
  <p><%= link_to 'check out the wyss institute', 'https://wyss.harvard.edu/' %></p>
  <p><%= link_to 'check out seed technology', 'https://www.getseed.io' %></p>
  <p><%= link_to 'oppose laveta terrace condo construction', 'https://www.opposelavetacondos.com' %></p>
</div>

out/production/fatcatty/app/views/pages/carfool.html.erb
<iframe width="560" height="315" src="https://www.youtube.com/embed/cVhr1QrFi2c?rel=0" frameborder="0" allowfullscreen></iframe><br>
<b>The Bernie Mac Show S2E03 "Carfool" 10/30/2002</b><br>
<p><i>By Mark Laubach</i></p>
<p>Bernie Mac is an authority on contemporary American family life. The character he portrays on his self-titled 2001 sitcom is no different. Mister Mac is king of his castle and expects fealty and respect from his family and his subjects in the neighborhood. While his attitude may impede progress to that goal, his mannerisms and philosophies are the standard that all American families strive for. Bernie Mac demonstrates the value of an education and the proper way to grow a community by ruling over them with inflexible rules as best illustrated by his management of a student carpool in the episode "Carfool".</p>
<p>Despite what the name of the episode implies, Bernie Mac is no fool in running his nieces' and nephew's school carpool. The bane of any education is apathetic tardiness. Bernie seeks to combat this blight on scholastic endeavors with his implementation of a five-second-rule. As he explains, addressing all of America, "I honk the horn, then they have five seconds to get to the car door before we pull away (Bernie Mac, 2002)". This prompts the student to run to the car, minimizing the commute time to school, reducing the probability of being tardy to class, and instilling a sense of personal responsibility in the youth. It also keeps the undesirable, "dirty" kids from messing up Mister Mac's impeccable automobile. The enforcement of this rule is universal, even when Bernie's own nephew, Jordan, misses his five-second window to obtain a ride, Bernie leaves him to chase after the car. The punishment for Jordan's tardiness is to be late or miss school together. Here, Bernie demonstrates the value of an education. Only students who are punctual, respectful, and clean to Mister Mac's standards may be ferried to school. Children who do not meet these expectations are left behind, foreshadowing how society will too leave them behind if they fall behind on these criteria later in life.
</p>

out/production/fatcatty/app/views/pages/shop.html.erb
<h2>shop</h2>
<div id="shopbody">
    <div style="float:left;padding-left:16px;" id='product-component-1586147078456'></div>
    <div style="float:left;padding-left:16px;padding-top:18px;" id='product-component-1586278605081'></div>
</div>
  <script type="text/javascript">
  /*<![CDATA[*/
  (function () {
    var scriptURL = 'https://sdks.shopifycdn.com/buy-button/latest/buy-button-storefront.min.js';
    if (window.ShopifyBuy) {
      if (window.ShopifyBuy.UI) {
        ShopifyBuyInit();
      } else {
        loadScript();
      }
    } else {
      loadScript();
    }
    function loadScript() {
      var script = document.createElement('script');
      script.async = true;
      script.src = scriptURL;
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(script);
      script.onload = ShopifyBuyInit;
    }
    function ShopifyBuyInit() {
      var client = ShopifyBuy.buildClient({
        domain: 'fatcatty.myshopify.com',
        storefrontAccessToken: '1927b1bd35c0fbc7dba67dfeb249745d',
      });
      ShopifyBuy.UI.onReady(client).then(function (ui) {
        ui.createComponent('product', {
          id: '4542040047719',
          node: document.getElementById('product-component-1586147078456'),
          moneyFormat: '%24%7B%7Bamount%7D%7D',
          options: {
    "product": {
      "styles": {
        "product": {
          "@media (min-width: 601px)": {
            "max-width": "calc(25% - 20px)",
            "margin-left": "20px",
            "margin-bottom": "50px"
          }
        },
        "button": {
          "font-size": "17px",
          "padding-top": "16.5px",
          "padding-bottom": "16.5px",
          "color": "#000000",
          ":hover": {
            "color": "#000000",
            "background-color": "#e6e6e6"
          },
          "background-color": "#ffffff",
          ":focus": {
            "background-color": "#e6e6e6"
          },
          "border-radius": "0px",
          "padding-left": "30px",
          "padding-right": "30px"
        },
        "quantityInput": {
          "font-size": "17px",
          "padding-top": "16.5px",
          "padding-bottom": "16.5px"
        }
      },
      "text": {
        "button": "Add to cart"
      }
    },
    "productSet": {
      "styles": {
        "products": {
          "@media (min-width: 601px)": {
            "margin-left": "-20px"
          }
        }
      }
    },
    "modalProduct": {
      "contents": {
        "img": false,
        "imgWithCarousel": true,
        "button": false,
        "buttonWithQuantity": true
      },
      "styles": {
        "product": {
          "@media (min-width: 601px)": {
            "max-width": "100%",
            "margin-left": "0px",
            "margin-bottom": "0px"
          }
        },
        "button": {
          "font-size": "17px",
          "padding-top": "16.5px",
          "padding-bottom": "16.5px",
          "color": "#000000",
          ":hover": {
            "color": "#000000",
            "background-color": "#e6e6e6"
          },
          "background-color": "#ffffff",
          ":focus": {
            "background-color": "#e6e6e6"
          },
          "border-radius": "0px",
          "padding-left": "30px",
          "padding-right": "30px"
        },
        "quantityInput": {
          "font-size": "17px",
          "padding-top": "16.5px",
          "padding-bottom": "16.5px"
        }
      },
      "text": {
        "button": "Add to cart"
      }
    },
    "cart": {
      "styles": {
        "button": {
          "font-size": "17px",
          "padding-top": "16.5px",
          "padding-bottom": "16.5px",
          "color": "#000000",
          ":hover": {
            "color": "#000000",
            "background-color": "#e6e6e6"
          },
          "background-color": "#ffffff",
          ":focus": {
            "background-color": "#e6e6e6"
          },
          "border-radius": "0px"
        }
      },
      "text": {
        "total": "Subtotal",
        "button": "Checkout"
      }
    },
    "toggle": {
      "styles": {
        "toggle": {
          "background-color": "#ffffff",
          ":hover": {
            "background-color": "#e6e6e6"
          },
          ":focus": {
            "background-color": "#e6e6e6"
          }
        },
        "count": {
          "font-size": "17px",
          "color": "#000000",
          ":hover": {
            "color": "#000000"
          }
        },
        "iconPath": {
          "fill": "#000000"
        }
      }
    }
  },
        });
      });
    }
  })();
  /*]]>*/
  </script>
<script type="text/javascript">
/*<![CDATA[*/
(function () {
  var scriptURL = 'https://sdks.shopifycdn.com/buy-button/latest/buy-button-storefront.min.js';
  if (window.ShopifyBuy) {
    if (window.ShopifyBuy.UI) {
      ShopifyBuyInit();
    } else {
      loadScript();
    }
  } else {
    loadScript();
  }
  function loadScript() {
    var script = document.createElement('script');
    script.async = true;
    script.src = scriptURL;
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(script);
    script.onload = ShopifyBuyInit;
  }
  function ShopifyBuyInit() {
    var client = ShopifyBuy.buildClient({
      domain: 'fatcatty.myshopify.com',
      storefrontAccessToken: '1927b1bd35c0fbc7dba67dfeb249745d',
    });
    ShopifyBuy.UI.onReady(client).then(function (ui) {
      ui.createComponent('product', {
        id: '4543732056167',
        node: document.getElementById('product-component-1586278605081'),
        moneyFormat: '%24%7B%7Bamount%7D%7D',
        options: {
  "product": {
    "styles": {
      "product": {
        "@media (min-width: 601px)": {
          "max-width": "calc(25% - 20px)",
          "margin-left": "20px",
          "margin-bottom": "50px"
        }
      },
      "button": {
        "font-size": "17px",
        "padding-top": "16.5px",
        "padding-bottom": "16.5px",
        "color": "#000000",
        ":hover": {
          "color": "#000000",
          "background-color": "#e6e6e6"
        },
        "background-color": "#ffffff",
        ":focus": {
          "background-color": "#e6e6e6"
        },
        "border-radius": "0px",
        "padding-left": "30px",
        "padding-right": "30px"
      },
      "quantityInput": {
        "font-size": "17px",
        "padding-top": "16.5px",
        "padding-bottom": "16.5px"
      }
    },
    "text": {
      "button": "Add to cart"
    }
  },
  "productSet": {
    "styles": {
      "products": {
        "@media (min-width: 601px)": {
          "margin-left": "-20px"
        }
      }
    }
  },
  "modalProduct": {
    "contents": {
      "img": false,
      "imgWithCarousel": true,
      "button": false,
      "buttonWithQuantity": true
    },
    "styles": {
      "product": {
        "@media (min-width: 601px)": {
          "max-width": "100%",
          "margin-left": "0px",
          "margin-bottom": "0px"
        }
      },
      "button": {
        "font-size": "17px",
        "padding-top": "16.5px",
        "padding-bottom": "16.5px",
        "color": "#000000",
        ":hover": {
          "color": "#000000",
          "background-color": "#e6e6e6"
        },
        "background-color": "#ffffff",
        ":focus": {
          "background-color": "#e6e6e6"
        },
        "border-radius": "0px",
        "padding-left": "30px",
        "padding-right": "30px"
      },
      "quantityInput": {
        "font-size": "17px",
        "padding-top": "16.5px",
        "padding-bottom": "16.5px"
      }
    },
    "text": {
      "button": "Add to cart"
    }
  },
  "cart": {
    "styles": {
      "button": {
        "font-size": "17px",
        "padding-top": "16.5px",
        "padding-bottom": "16.5px",
        "color": "#000000",
        ":hover": {
          "color": "#000000",
          "background-color": "#e6e6e6"
        },
        "background-color": "#ffffff",
        ":focus": {
          "background-color": "#e6e6e6"
        },
        "border-radius": "0px"
      }
    },
    "text": {
      "total": "Subtotal",
      "button": "Checkout"
    }
  },
  "toggle": {
    "styles": {
      "toggle": {
        "background-color": "#ffffff",
        ":hover": {
          "background-color": "#e6e6e6"
        },
        ":focus": {
          "background-color": "#e6e6e6"
        }
      },
      "count": {
        "font-size": "17px",
        "color": "#000000",
        ":hover": {
          "color": "#000000"
        }
      },
      "iconPath": {
        "fill": "#000000"
      }
    }
  }
},
      });
    });
  }
})();
/*]]>*/
</script>

out/production/fatcatty/app/views/posts/_post.html.erb
<%= div_for post do %>
    <span class="postTitle"><%= image_tag("archive.png") %> <%= link_to h(post.title), post %></span>
    <div id="<%= post.id %>">
      <%= h(raw post.body) %>
    </div>
    <div>
      score: <%= raw number_with_precision(post.score, :precision => 0) %>/100
    </div>
    <div class="tags">
     tags: <%=raw tag_links(post.all_tags)%>
    </div>
    <div class="from">
      from <%= time_ago_in_words(post.created_at)%> ago
    </div>
    <div class="postSpacer"></div>
<% end %>

out/production/fatcatty/app/views/posts/index.html.erb
<% if admin_signed_in? %>
<%= link_to "new post", posts_new_path %>
<% else %>
<% end %>
<h2>blog</h2>
<%= render partial: @posts %>
</div>
<div><center><%= paginate @postspag %></center></div>
<div class="tags-cloud">
  <h4>tag cloud</h4>
  <% tag_cloud Tag.counts, %w{css1 css2 css3 css4} do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div>

out/production/fatcatty/app/views/posts/new.html.erb
<% if admin_signed_in? %>
<div style="width:50%;text-align:left;padding-top:32px;padding-left:24px;">
  <%= form_for(Post.new, remote: true) do |f| %>
    <div class="postField">
      <%= f.text_field :title, placeholder: "title", size: 40 %>
    </div>
    <div class="postField", id="body">
      <%= f.text_area :body, placeholder: "Your post", rows: 7 %>
    </div>
    <div class="postField" style="padding-top:8px;">
      <%= f.text_field :all_tags, placeholder: "Tags separated with comma", size: 40 %>
    </div>
    <div class="postField">
      <%= f.number_field :score, placeholder: "score x - x" %>
    </div>
    <div class="postField">
      <%= f.submit "Post", class: "button"%>
    </div>
  <% end %>
</div>
<script>
    CKEDITOR.replace( 'post_body' );
</script>
<% else %>
<p>get outta here</p>
<% end %>

out/production/fatcatty/app/views/posts/show.html.erb
  <div html="true">
    <strong><%= h(@post.title) %></strong><br />
    <div class="mb pb">
      <%= h(raw @post.body) %>
    </div>
    <div class="tags">
      tags: <%=raw tag_links(@post.all_tags)%>
    </div>
    <div class="text-muted">from <%= time_ago_in_words(@post.created_at)%> ago</div>
    <div class="text-muted">on <%= @post.created_at.strftime("%F") %> </div><br />
    <div class="postSpacer">~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</div>
      <% if admin_signed_in? %>
      <%= button_to "Delete", post_path(@post), method: :delete %>
      <% else %>
    <% end %>
    </div>
  </div>

out/production/fatcatty/app/views/works/index.html.erb
<% if admin_signed_in? %>
<%= link_to "new work of art", works_new_path %>
<% else %>
<% end %>
<h2>works</h2>
<div class="workDiv">
<% @works.each do |work| %>
  <div><%= work.title if work %></div>
  <div><%= link_to image_tag(work.image), work if work %></div>
  <div><%= work.created_at if work %></div>
<% end %>
<div><%= paginate @works %></div>